ANALYZE TABLE PEOPLE COMPUTE STATISTICS;

EXPLAIN PLAN 
SET STATEMENT_ID = '2D2' FOR
SELECT personName
FROM people
WHERE birthYear > 1945;

SELECT ID||' '||PARENT_ID||' '||LPAD(' ', 2*(LEVEL-1))||OPERATION||'
'||OPTIONS||' '||OBJECT_NAME "QUERY PLAN" FROM PLAN_TABLE WHERE
STATEMENT_ID='2D2' START WITH ID = 0 CONNECT BY PRIOR
ID=PARENT_ID;


CREATE INDEX idx_birthYear ON PEOPLE(BIRTHYEAR);


EXPLAIN PLAN
SET STATEMENT_ID = '2D2AB' FOR
SELECT personName
FROM people
WHERE BIRTHYEAR > 1945;

SELECT ID||' '||PARENT_ID||' '||LPAD(' ', 2*(LEVEL-1))||OPERATION||'
'||OPTIONS||' '||OBJECT_NAME "QUERY PLAN" FROM PLAN_TABLE WHERE
STATEMENT_ID='2D2AB' START WITH ID = 0 CONNECT BY PRIOR
ID=PARENT_ID;

DROP INDEX idx_birthYear;
