ANALYZE TABLE MOVIE COMPUTE STATISTICS;

EXPLAIN PLAN
SET STATEMENT_ID = '2D1' FOR
SELECT movieTitle
FROM movie
WHERE year > 1990;

SELECT ID||' '||PARENT_ID||' '||LPAD(' ', 2*(LEVEL-1))||OPERATION||'
'||OPTIONS||' '||OBJECT_NAME "QUERY PLAN" FROM PLAN_TABLE WHERE
STATEMENT_ID='2D1' START WITH ID = 0 CONNECT BY PRIOR
ID=PARENT_ID;



CREATE INDEX idx_year ON MOVIE(year);


EXPLAIN PLAN
SET STATEMENT_ID = '2D1AB' FOR
SELECT movieTitle
FROM movie
WHERE year > 1990;

SELECT ID||' '||PARENT_ID||' '||LPAD(' ', 2*(LEVEL-1))||OPERATION||'
'||OPTIONS||' '||OBJECT_NAME "QUERY PLAN" FROM PLAN_TABLE WHERE
STATEMENT_ID='2D1AB' START WITH ID = 0 CONNECT BY PRIOR
ID=PARENT_ID;

DROP INDEX idx_year;