ALTER SESSION SET OPTIMIZER_MODE = RULE;

EXPLAIN PLAN
SET STATEMENT_ID = '2B1' FOR
SELECT movieTitle FROM movie 
WHERE year > 1990;

SELECT ID||' '||PARENT_ID||' '||LPAD(' ', 2*(LEVEL-1))||OPERATION||'
'||OPTIONS||' '||OBJECT_NAME "QUERY PLAN" FROM PLAN_TABLE WHERE
STATEMENT_ID='2B1' START WITH ID = 0 CONNECT BY PRIOR
ID=PARENT_ID;


EXPLAIN PLAN
SET STATEMENT_ID = '2B2' FOR
SELECT personName 
FROM people 
WHERE birthYear > 1945;

SELECT ID||' '||PARENT_ID||' '||LPAD(' ', 2*(LEVEL-1))||OPERATION||'
'||OPTIONS||' '||OBJECT_NAME "QUERY PLAN" FROM PLAN_TABLE WHERE
STATEMENT_ID='2B2' START WITH ID = 0 CONNECT BY PRIOR
ID=PARENT_ID;

/* Now I will go to E */







EXPLAIN PLAN
SET STATEMENT_ID = '2B3' FOR
SELECT movieID, movieTitle FROM movie 
WHERE movieID != 0046778 and year > 1985;

SELECT ID||' '||PARENT_ID||' '||LPAD(' ', 2*(LEVEL-1))||OPERATION||'
'||OPTIONS||' '||OBJECT_NAME "QUERY PLAN" FROM PLAN_TABLE WHERE
STATEMENT_ID='2B3' START WITH ID = 0 CONNECT BY PRIOR
ID=PARENT_ID;

EXPLAIN PLAN
SET STATEMENT_ID = '2B4' FOR
SELECT movieID, movieTitle FROM movie 
WHERE movieID = 0046778 and year > 1985;

SELECT ID||' '||PARENT_ID||' '||LPAD(' ', 2*(LEVEL-1))||OPERATION||'
'||OPTIONS||' '||OBJECT_NAME "QUERY PLAN" FROM PLAN_TABLE WHERE
STATEMENT_ID='2B4' START WITH ID = 0 CONNECT BY PRIOR
ID=PARENT_ID;

